config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  
  resources :resposts

  resources :comentarios

  resources :resposta

  resources :topicos

  resources :filmes

  resources :ators

  resources :estudios

  resources :produtors

  resources :diretors

  resources :generos

end

app/models/ator.rb
class Ator < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :filmes, :through => :filme_ators, source: :filme
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :respost, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
end

app/models/diretor.rb
class Diretor < ActiveRecord::Base
	has_many :filme_diretors, :dependent => :destroy
	has_many :filmes, :through => :filme_diretors, source: :filme
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :filme_estudios, :dependent => :destroy
	has_many :filmes, :through => :filme_estudios, source: :filme
end

app/models/filme.rb
class Filme < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :ators, :through => :filme_ators

	has_many :filme_generos, :dependent => :destroy
	has_many :generos, :through => :filme_generos

	has_many :filme_diretors, :dependent => :destroy
	has_many :diretors, :through => :filme_diretors

	has_many :filme_estudios, :dependent => :destroy
	has_many :estudios, :through => :filme_estudios

	has_many :filme_produtors, :dependent => :destroy
	has_many :produtors, :through => :filme_produtors

	has_many :topicos
end

app/models/filme_ator.rb
class FilmeAtor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :ator
end

app/models/filme_diretor.rb
class FilmeDiretor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :diretor
end

app/models/filme_estudio.rb
class FilmeEstudio < ActiveRecord::Base
	belongs_to :filme
	belongs_to :estudio
end

app/models/filme_genero.rb
class FilmeGenero < ActiveRecord::Base
	belongs_to :filme
	belongs_to :genero
end

app/models/filme_produtor.rb
class FilmeProdutor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :produtor
end

app/models/genero.rb
class Genero < ActiveRecord::Base
	has_many :filme_generos, :dependent => :destroy
	has_many :filmes, :through => :filme_generos, source: :filme
end

app/models/produtor.rb
class Produtor < ActiveRecord::Base
	has_many :filme_produtors, :dependent => :destroy
	has_many :filmes, :through => :filme_produtors, source: :filme
end

app/models/respost.rb
class Respost < ActiveRecord::Base
	belongs_to :topico, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :comentarios
end

app/models/topico.rb
class Topico < ActiveRecord::Base
	belongs_to :filme, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :resposts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  has_many :topicos
  has_many :resposts
  has_many :comentarios
end

app/controllers/ators_controller.rb
class AtorsController < ApplicationController
  before_action :set_ator, only: [:show, :edit, :update, :destroy]

  # GET /ators
  # GET /ators.json
  def index
    @ators = Ator.all
  end

  # GET /ators/1
  # GET /ators/1.json
  def show
  end

  # GET /ators/new
  def new
    @ator = Ator.new
  end

  # GET /ators/1/edit
  def edit
  end

  # POST /ators
  # POST /ators.json
  def create
    @ator = Ator.new(ator_params)

    respond_to do |format|
      if @ator.save
        format.html { redirect_to @ator, notice: 'Ator was successfully created.' }
        format.json { render :show, status: :created, location: @ator }
      else
        format.html { render :new }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ators/1
  # PATCH/PUT /ators/1.json
  def update
    respond_to do |format|
      if @ator.update(ator_params)
        format.html { redirect_to @ator, notice: 'Ator was successfully updated.' }
        format.json { render :show, status: :ok, location: @ator }
      else
        format.html { render :edit }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ators/1
  # DELETE /ators/1.json
  def destroy
    @ator.destroy
    respond_to do |format|
      format.html { redirect_to ators_url, notice: 'Ator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ator
      @ator = Ator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ator_params
      params.require(:ator).permit(:ator)
    end
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/helpers/diretors_helper.rb
module DiretorsHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/resposts_helper.rb
module RespostsHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/ators/_form.html.erb
<%= form_for(@ator) do |f| %>
  <% if @ator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ator.errors.count, "error") %> prohibited this ator from being saved:</h2>

      <ul>
      <% @ator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ator %><br>
    <%= f.text_field :ator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ators/edit.html.erb
<h1>Editing ator</h1>

<%= render 'form' %>

<%= link_to 'Show', @ator %> |
<%= link_to 'Back', ators_path %>

app/views/ators/index.html.erb
<h1>Listing ators</h1>

<table>
  <thead>
    <tr>
      <th>Ator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ators.each do |ator| %>
      <tr>
        <td><%= ator.ator %></td>
        <td><%= link_to 'Show', ator %></td>
        <td><%= link_to 'Edit', edit_ator_path(ator) %></td>
        <td><%= link_to 'Destroy', ator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ator', new_ator_path %>

app/views/ators/new.html.erb
<h1>New ator</h1>

<%= render 'form' %>

<%= link_to 'Back', ators_path %>

app/views/ators/show.html.erb
<p>
  <strong>Ator:</strong>
  <%= @ator.ator %>
</p>

<%= link_to 'Edit', edit_ator_path(@ator) %> |
<%= link_to 'Back', ators_path %>