config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  
  resources :resposts

  resources :comentarios

  resources :resposta

  resources :topicos

  resources :filmes

  resources :ators

  resources :estudios

  resources :produtors

  resources :diretors

  resources :generos

end

app/models/ator.rb
class Ator < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :filmes, :through => :filme_ators, source: :filme
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :respost, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
end

app/models/diretor.rb
class Diretor < ActiveRecord::Base
	has_many :filme_diretors, :dependent => :destroy
	has_many :filmes, :through => :filme_diretors, source: :filme
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :filme_estudios, :dependent => :destroy
	has_many :filmes, :through => :filme_estudios, source: :filme
end

app/models/filme.rb
class Filme < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :ators, :through => :filme_ators

	has_many :filme_generos, :dependent => :destroy
	has_many :generos, :through => :filme_generos

	has_many :filme_diretors, :dependent => :destroy
	has_many :diretors, :through => :filme_diretors

	has_many :filme_estudios, :dependent => :destroy
	has_many :estudios, :through => :filme_estudios

	has_many :filme_produtors, :dependent => :destroy
	has_many :produtors, :through => :filme_produtors

	has_many :topicos
end

app/models/filme_ator.rb
class FilmeAtor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :ator
end

app/models/filme_diretor.rb
class FilmeDiretor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :diretor
end

app/models/filme_estudio.rb
class FilmeEstudio < ActiveRecord::Base
	belongs_to :filme
	belongs_to :estudio
end

app/models/filme_genero.rb
class FilmeGenero < ActiveRecord::Base
	belongs_to :filme
	belongs_to :genero
end

app/models/filme_produtor.rb
class FilmeProdutor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :produtor
end

app/models/genero.rb
class Genero < ActiveRecord::Base
	has_many :filme_generos, :dependent => :destroy
	has_many :filmes, :through => :filme_generos, source: :filme
end

app/models/produtor.rb
class Produtor < ActiveRecord::Base
	has_many :filme_produtors, :dependent => :destroy
	has_many :filmes, :through => :filme_produtors, source: :filme
end

app/models/respost.rb
class Respost < ActiveRecord::Base
	belongs_to :topico, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :comentarios
end

app/models/topico.rb
class Topico < ActiveRecord::Base
	belongs_to :filme, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :resposts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  has_many :topicos
  has_many :resposts
  has_many :comentarios
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)
    @comentario.user = current_user

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:corpo, :quantidadelikes, :respost_id)
    end
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/diretors_helper.rb
module DiretorsHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :corpo %><br>
    <%= f.text_area :corpo %>
  </div>
  <div class="field">
    <%= f.label :quantidadelikes %><br>
    <%= f.number_field :quantidadelikes %>
  </div>
  <%= f.hidden_field :respost_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Corpo</th>
      <th>Quantidadelikes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.corpo %></td>
        <td><%= comentario.quantidadelikes %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p>
  <strong>Corpo:</strong>
  <%= @comentario.corpo %>
</p>

<p>
  <strong>Quantidadelikes:</strong>
  <%= @comentario.quantidadelikes %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>