config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  
  resources :resposts

  resources :comentarios

  resources :resposta

  resources :topicos

  resources :filmes

  resources :ators

  resources :estudios

  resources :produtors

  resources :diretors

  resources :generos

end

app/models/ator.rb
class Ator < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :filmes, :through => :filme_ators, source: :filme
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :respost, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
end

app/models/diretor.rb
class Diretor < ActiveRecord::Base
	has_many :filme_diretors, :dependent => :destroy
	has_many :filmes, :through => :filme_diretors, source: :filme
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :filme_estudios, :dependent => :destroy
	has_many :filmes, :through => :filme_estudios, source: :filme
end

app/models/filme.rb
class Filme < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :ators, :through => :filme_ators

	has_many :filme_generos, :dependent => :destroy
	has_many :generos, :through => :filme_generos

	has_many :filme_diretors, :dependent => :destroy
	has_many :diretors, :through => :filme_diretors

	has_many :filme_estudios, :dependent => :destroy
	has_many :estudios, :through => :filme_estudios

	has_many :filme_produtors, :dependent => :destroy
	has_many :produtors, :through => :filme_produtors

	has_many :topicos
end

app/models/filme_ator.rb
class FilmeAtor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :ator
end

app/models/filme_diretor.rb
class FilmeDiretor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :diretor
end

app/models/filme_estudio.rb
class FilmeEstudio < ActiveRecord::Base
	belongs_to :filme
	belongs_to :estudio
end

app/models/filme_genero.rb
class FilmeGenero < ActiveRecord::Base
	belongs_to :filme
	belongs_to :genero
end

app/models/filme_produtor.rb
class FilmeProdutor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :produtor
end

app/models/genero.rb
class Genero < ActiveRecord::Base
	has_many :filme_generos, :dependent => :destroy
	has_many :filmes, :through => :filme_generos, source: :filme
end

app/models/produtor.rb
class Produtor < ActiveRecord::Base
	has_many :filme_produtors, :dependent => :destroy
	has_many :filmes, :through => :filme_produtors, source: :filme
end

app/models/respost.rb
class Respost < ActiveRecord::Base
	belongs_to :topico, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :comentarios
end

app/models/topico.rb
class Topico < ActiveRecord::Base
	belongs_to :filme, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :resposts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  has_many :topicos
  has_many :resposts
  has_many :comentarios
end

app/controllers/produtors_controller.rb
class ProdutorsController < ApplicationController
  before_action :set_produtor, only: [:show, :edit, :update, :destroy]

  # GET /produtors
  # GET /produtors.json
  def index
    @produtors = Produtor.all
  end

  # GET /produtors/1
  # GET /produtors/1.json
  def show
  end

  # GET /produtors/new
  def new
    @produtor = Produtor.new
  end

  # GET /produtors/1/edit
  def edit
  end

  # POST /produtors
  # POST /produtors.json
  def create
    @produtor = Produtor.new(produtor_params)

    respond_to do |format|
      if @produtor.save
        format.html { redirect_to @produtor, notice: 'Produtor was successfully created.' }
        format.json { render :show, status: :created, location: @produtor }
      else
        format.html { render :new }
        format.json { render json: @produtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtors/1
  # PATCH/PUT /produtors/1.json
  def update
    respond_to do |format|
      if @produtor.update(produtor_params)
        format.html { redirect_to @produtor, notice: 'Produtor was successfully updated.' }
        format.json { render :show, status: :ok, location: @produtor }
      else
        format.html { render :edit }
        format.json { render json: @produtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtors/1
  # DELETE /produtors/1.json
  def destroy
    @produtor.destroy
    respond_to do |format|
      format.html { redirect_to produtors_url, notice: 'Produtor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produtor
      @produtor = Produtor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produtor_params
      params.require(:produtor).permit(:produtor)
    end
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/helpers/diretors_helper.rb
module DiretorsHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/produtors_helper.rb
module ProdutorsHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/produtors/_form.html.erb
<%= form_for(@produtor) do |f| %>
  <% if @produtor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produtor.errors.count, "error") %> prohibited this produtor from being saved:</h2>

      <ul>
      <% @produtor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :produtor %><br>
    <%= f.text_field :produtor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtors/edit.html.erb
<h1>Editing produtor</h1>

<%= render 'form' %>

<%= link_to 'Show', @produtor %> |
<%= link_to 'Back', produtors_path %>

app/views/produtors/index.html.erb
<h1>Listing produtors</h1>

<table>
  <thead>
    <tr>
      <th>Produtor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtors.each do |produtor| %>
      <tr>
        <td><%= produtor.produtor %></td>
        <td><%= link_to 'Show', produtor %></td>
        <td><%= link_to 'Edit', edit_produtor_path(produtor) %></td>
        <td><%= link_to 'Destroy', produtor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produtor', new_produtor_path %>

app/views/produtors/new.html.erb
<h1>New produtor</h1>

<%= render 'form' %>

<%= link_to 'Back', produtors_path %>

app/views/produtors/show.html.erb
<p>
  <strong>Produtor:</strong>
  <%= @produtor.produtor %>
</p>

<%= link_to 'Edit', edit_produtor_path(@produtor) %> |
<%= link_to 'Back', produtors_path %>