config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  
  resources :resposts

  resources :comentarios

  resources :resposta

  resources :topicos

  resources :filmes

  resources :ators

  resources :estudios

  resources :produtors

  resources :diretors

  resources :generos

end

app/models/ator.rb
class Ator < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :filmes, :through => :filme_ators, source: :filme
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :respost, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
end

app/models/diretor.rb
class Diretor < ActiveRecord::Base
	has_many :filme_diretors, :dependent => :destroy
	has_many :filmes, :through => :filme_diretors, source: :filme
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :filme_estudios, :dependent => :destroy
	has_many :filmes, :through => :filme_estudios, source: :filme
end

app/models/filme.rb
class Filme < ActiveRecord::Base
	has_many :filme_ators, :dependent => :destroy
	has_many :ators, :through => :filme_ators

	has_many :filme_generos, :dependent => :destroy
	has_many :generos, :through => :filme_generos

	has_many :filme_diretors, :dependent => :destroy
	has_many :diretors, :through => :filme_diretors

	has_many :filme_estudios, :dependent => :destroy
	has_many :estudios, :through => :filme_estudios

	has_many :filme_produtors, :dependent => :destroy
	has_many :produtors, :through => :filme_produtors

	has_many :topicos
end

app/models/filme_ator.rb
class FilmeAtor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :ator
end

app/models/filme_diretor.rb
class FilmeDiretor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :diretor
end

app/models/filme_estudio.rb
class FilmeEstudio < ActiveRecord::Base
	belongs_to :filme
	belongs_to :estudio
end

app/models/filme_genero.rb
class FilmeGenero < ActiveRecord::Base
	belongs_to :filme
	belongs_to :genero
end

app/models/filme_produtor.rb
class FilmeProdutor < ActiveRecord::Base
	belongs_to :filme
	belongs_to :produtor
end

app/models/genero.rb
class Genero < ActiveRecord::Base
	has_many :filme_generos, :dependent => :destroy
	has_many :filmes, :through => :filme_generos, source: :filme
end

app/models/produtor.rb
class Produtor < ActiveRecord::Base
	has_many :filme_produtors, :dependent => :destroy
	has_many :filmes, :through => :filme_produtors, source: :filme
end

app/models/respost.rb
class Respost < ActiveRecord::Base
	belongs_to :topico, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :comentarios
end

app/models/topico.rb
class Topico < ActiveRecord::Base
	belongs_to :filme, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :resposts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  has_many :topicos
  has_many :resposts
  has_many :comentarios
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]

  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
  end

  # GET /topicos/new
  def new
    @topico = Topico.new
  end

  # GET /topicos/1/edit
  def edit
  end

  # POST /topicos
  # POST /topicos.json
  def create
    @topico = Topico.new(topico_params)
    @topico.user = current_user

    respond_to do |format|
      if @topico.save
        format.html { redirect_to @topico, notice: 'Topico was successfully created.' }
        format.json { render :show, status: :created, location: @topico }
      else
        format.html { render :new }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
    respond_to do |format|
      if @topico.update(topico_params)
        format.html { redirect_to @topico, notice: 'Topico was successfully updated.' }
        format.json { render :show, status: :ok, location: @topico }
      else
        format.html { render :edit }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Topico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
      @respost = @topico.resposts.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:corpo, :titulo, :quantidade_likes, :tags, :quantidade_visualizacoes, :filme_id)
    end
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/helpers/diretors_helper.rb
module DiretorsHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/resposts_helper.rb
module RespostsHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/topicos/_form.html.erb
<%= form_for(@topico) do |f| %>
  <% if @topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% @topico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if params[:filme] %>
  <input type="number" id="topico_filme_id" name="topico[filme_id]" value="<%= params[:filme] %>" />
  <% end %>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :corpo %><br>
    <%= f.text_area :corpo %>
  </div>
  <div class="field">
    <%= f.label :quantidade_likes %><br>
    <%= f.number_field :quantidade_likes %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :quantidade_visualizacoes %><br>
    <%= f.number_field :quantidade_visualizacoes %>
  </div>
  <%= f.hidden_field :filme_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topicos/edit.html.erb
<h1>Editing topico</h1>

<%= render 'form' %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>

app/views/topicos/index.html.erb
<h1>Listing topicos</h1>

<table>
  <thead>
    <tr>
      <th>Corpo</th>
      <th>Titulo</th>
      <th>Quantidade likes</th>
      <th>Tags</th>
      <th>Quantidade visualizacoes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topicos.each do |topico| %>
      <tr>
        <td><%= topico.corpo %></td>
        <td><%= topico.titulo %></td>
        <td><%= topico.quantidade_likes %></td>
        <td><%= topico.tags %></td>
        <td><%= topico.quantidade_visualizacoes %></td>
        <td><%= link_to 'Show', topico %></td>
        <td><%= link_to 'Edit', edit_topico_path(topico) %></td>
        <td><%= link_to 'Destroy', topico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topico', new_topico_path %>

app/views/topicos/new.html.erb
<h1>New topico</h1>

<%= render 'form' %>

<%= link_to 'Back', topicos_path %>

app/views/topicos/show.html.erb
<p>
  <strong>Corpo:</strong>
  <%= @topico.corpo %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @topico.titulo %>
</p>

<p>
  <strong>Quantidade likes:</strong>
  <%= @topico.quantidade_likes %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @topico.tags %>
</p>

<p>
  <strong>Quantidade visualizacoes:</strong>
  <%= @topico.quantidade_visualizacoes %>
</p>

<h3>Respostas</h3>
<% @topico.resposts.each do |respost| %>
  <div>
    <p><%= respost.corpo %><p>
  </div>
  <% respost.comentarios.each do |comentario| %>
    <div>
      <p><%= comentario.corpo %><p>
    </div>
  <% end %>
<% end %>
<%= render 'resposts/form' %>

<%= link_to 'Edit', edit_topico_path(@topico) %> |
<%= link_to 'Back', topicos_path %>